name: ChatTest
description: Easily test how messages will look in chat.
authors: [ TehBrian ]
website: https://www.spigotmc.org/resources/80783/

version: ${version}
main: xyz.tehbrian.chattest.ChatTest
api-version: 1.17

commands:
  ct:
    description: Send a message to yourself.
    permission: chattest.ctc
    usage: /<command> <message>
  cta:
    description: Send a message to all players.
    permission: chattest.cta
    usage: /<command> <message>
  ctc:
    description: Toggle personal color code translation.
    permission: chattest.ctc
    usage: /<command>
  ctr:
    description: Reload the config.
    permission: chattest.ctr
    usage: /<command>
permissions:
  chattest.ct:
    description: Permission to use /ct.
    default: op
  chattest.cta:
    description: Permission to use /cta.
    default: op
  chattest.ctc:
    description: Permission to use /ctc.
    default: op
  chattest.ctr:
    description: Permission to use /ctr.
    default: op
