name: LegacyChatTest
description: ${description}
authors: [ TehBrian ]
website: https://spigotmc.org/resources/80783

version: ${version}
main: xyz.tehbrian.legacychattest.LegacyChatTest
api-version: 1.18

commands:
  ct:
    description: Send a message to yourself.
    permission: legacychattest.ctc
    usage: /<command> <message>
  cta:
    description: Send a message to all players.
    permission: legacychattest.cta
    usage: /<command> <message>
  ctc:
    description: Toggle personal color code translation.
    permission: legacychattest.ctc
    usage: /<command>
  ctr:
    description: Reload the config.
    permission: legacychattest.ctr
    usage: /<command>
permissions:
  legacychattest.ct:
    description: Permission to run /ct.
    default: op
  legacychattest.cta:
    description: Permission to run /cta.
    default: op
  legacychattest.ctc:
    description: Permission to run /ctc.
    default: op
  legacychattest.ctr:
    description: Permission to run /ctr.
    default: op
