name: LegacyChatTest
description: Easily test how legacy-formatted messages will look in chat.
authors: [ TehBrian ]
website: https://spigotmc.org/resources/80783

version: ${version}
main: xyz.tehbrian.legacychattest.LegacyChatTest
api-version: 1.17

commands:
  ct:
    description: Send a message to yourself.
    permission: chattest.ctc
    usage: /<command> <message>
  cta:
    description: Send a message to all players.
    permission: chattest.cta
    usage: /<command> <message>
  ctc:
    description: Toggle personal color code translation.
    permission: chattest.ctc
    usage: /<command>
  ctr:
    description: Reload the config.
    permission: chattest.ctr
    usage: /<command>
permissions:
  chattest.ct:
    description: Permission to run /ct.
    default: op
  chattest.cta:
    description: Permission to run /cta.
    default: op
  chattest.ctc:
    description: Permission to run /ctc.
    default: op
  chattest.ctr:
    description: Permission to run /ctr.
    default: op
